version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: KGgjDf8hoFZW+XtetYeBGvb+Q5K7D5pKprkC164EM7s6+klUTvpJ+9L6qr7bYZHa
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

install:
  - ps: Install-Product node
  
before_build:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: cd swlSimulator
  - npm install
  
build_script:
  - ps: cd ..
  - ps: dotnet build swlsimNET.sln --configuration Release
  - ps: cd swlSimulator
  - ps: node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
  - ps: node node_modules/webpack/bin/webpack.js --env.prod
  - ps: dotnet publish --configuration Release
  - ps: copy ..\manifest.xml "bin\Any CPU\Release\netcoreapp2.0\manifest.xml"
  - ps: mkdir C:\projects\swlsimnet\artifacts
  
artifacts:
- path: artifacts\swlSimulator.zip
  name: swlSimulator
  type: WebDeployPackage

test_script:
  - dotnet test "C:\projects\swlsimnet\swlsimNET.Tests\swlSimulator.Tests.csproj
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -target:"C:/projects/swlsimnet/swlsimNET.Tests/bin/Any CPU/Release/swlSimulator.Tests.dll" -output:coverage.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%


